// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductManagement.Server.Data;

#nullable disable

namespace ProductManagement.Server.Migrations
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ProductManagement.Server.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Food"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Electronics"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Outdoor"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Books"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Health"
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Furniture"
                        });
                });

            modelBuilder.Entity("ProductManagement.Server.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQty")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DateAdded = new DateTime(2024, 11, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 3.00m,
                            ProductCode = "SKU0010",
                            ProductName = "Bread",
                            StockQty = 15
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            DateAdded = new DateTime(2024, 11, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 4.00m,
                            ProductCode = "SKU0011",
                            ProductName = "Ham",
                            StockQty = 18
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            DateAdded = new DateTime(2024, 11, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 5.00m,
                            ProductCode = "SKU0012",
                            ProductName = "Cheese",
                            StockQty = 17
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            DateAdded = new DateTime(2024, 11, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 30.50m,
                            ProductCode = "SKU0013",
                            ProductName = "Joggers",
                            StockQty = 12
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            DateAdded = new DateTime(2024, 11, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 20.99m,
                            ProductCode = "SKU0014",
                            ProductName = "T-Shirt",
                            StockQty = 4
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            DateAdded = new DateTime(2024, 11, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 46.75m,
                            ProductCode = "SKU0015",
                            ProductName = "Coat",
                            StockQty = 11
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            DateAdded = new DateTime(2024, 11, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 15.00m,
                            ProductCode = "SKU0016",
                            ProductName = "Iron",
                            StockQty = 12
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            DateAdded = new DateTime(2024, 11, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 30.15m,
                            ProductCode = "SKU0017",
                            ProductName = "Microwave",
                            StockQty = 18
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            DateAdded = new DateTime(2024, 11, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 58.00m,
                            ProductCode = "SKU0018",
                            ProductName = "Hoover",
                            StockQty = 14
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            DateAdded = new DateTime(2024, 11, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 5.00m,
                            ProductCode = "SKU0019",
                            ProductName = "Football",
                            StockQty = 101
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            DateAdded = new DateTime(2024, 11, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 30.00m,
                            ProductCode = "SKU0020",
                            ProductName = "Tent",
                            StockQty = 64
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            DateAdded = new DateTime(2024, 11, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 144.95m,
                            ProductCode = "SKU0021",
                            ProductName = "Surfboard",
                            StockQty = 23
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            DateAdded = new DateTime(2024, 11, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 10.00m,
                            ProductCode = "SKU0022",
                            ProductName = "Harry Potter",
                            StockQty = 55
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            DateAdded = new DateTime(2024, 11, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 12.80m,
                            ProductCode = "SKU0023",
                            ProductName = "Alan Watts",
                            StockQty = 12
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            DateAdded = new DateTime(2024, 11, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 8.33m,
                            ProductCode = "SKU0024",
                            ProductName = "Fundamental Physics",
                            StockQty = 17
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            DateAdded = new DateTime(2024, 11, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 2.00m,
                            ProductCode = "SKU0025",
                            ProductName = "Vitamin C",
                            StockQty = 42
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 6,
                            DateAdded = new DateTime(2024, 11, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 5.00m,
                            ProductCode = "SKU0026",
                            ProductName = "Ibuprofen",
                            StockQty = 115
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 6,
                            DateAdded = new DateTime(2024, 11, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 10.65m,
                            ProductCode = "SKU0027",
                            ProductName = "Sunscreen SPF 30",
                            StockQty = 53
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 7,
                            DateAdded = new DateTime(2024, 11, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 42.00m,
                            ProductCode = "SKU0028",
                            ProductName = "Chair",
                            StockQty = 28
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 7,
                            DateAdded = new DateTime(2024, 11, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 110.80m,
                            ProductCode = "SKU0029",
                            ProductName = "Bed",
                            StockQty = 4
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 7,
                            DateAdded = new DateTime(2024, 11, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 75.00m,
                            ProductCode = "SKU0030",
                            ProductName = "Shelf",
                            StockQty = 9
                        });
                });

            modelBuilder.Entity("ProductManagement.Server.Model.Product", b =>
                {
                    b.HasOne("ProductManagement.Server.Model.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
